name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified

    - name: Scan for secrets with GitLeaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for hardcoded credentials
      run: |
        echo "Scanning for potential secrets..."
        if grep -r -i -E "(api[_-]?key|secret|password|token|credential|private[_-]?key)" --include="*.py" --include="*.ts" --include="*.js" --include="*.json" --exclude-dir=node_modules --exclude-dir=.git .; then
          echo "❌ Potential secrets found in code!"
          exit 1
        else
          echo "✅ No hardcoded secrets detected"
        fi

    - name: Validate gitignore coverage
      run: |
        echo "Checking gitignore coverage..."
        if find . -name "*.key" -o -name "*.pem" -o -name ".env*" -o -name "*secret*" | grep -v ".gitignore" | head -5; then
          echo "❌ Potential secret files not in gitignore!"
          exit 1
        else
          echo "✅ No untracked secret files found"
        fi